[workspace]
members = ["contracts/*", "packages/*"]

[profile.release.package.rest-nft-base]
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
